### ISSUE TITLE
✅ [Test] - cgi_tester 실행

### ISSUE THREAD

**Issue by ohhamma** [web42serv/webserv#15]
## 📝 Description
`cgi_tester`를 어떻게 돌려야하는지 알아보자

## ✅ To-do
- [x] `cgi_tester` 이것저것 실행해보기
- [x] `.bla` 파일만 cgi 돌리게끔 수정하기
- [x] `tester` 실행시 실행되는건지 확인

## 📚 Etc
- 인자 없이 `cgi_tester`만 돌리면 다음과 같은 에러 메시지 뜸
```
cgi: no REQUEST_METHOD in environment
```

**Comment by ohhamma** [comment]
- 기존 `tester`에서 실행되는 것으로 확인
- 직접 실행 불가능
