### ISSUE TITLE
🎨 [Refactor] - cgi 파일 정리

### ISSUE THREAD

**Issue by ohhamma** [web42serv/webserv#17]
## 📝 Description
- cgi 파일들을 `cgi-bin/` 디렉토리에 넣어서 보관하면 좋을 것 같습니다

## ✅ To-do
- [x] `cgi-bin/` 디렉토리에 cgi 파일 옮기기
- [x] cgi 파일 내용 중 `action`은 경로 고려해서 수정하기
- [x] cgi 모두 잘 돌아가는지 테스트 후 pr 날려주세요

## 📚 Etc
- 특이사항
