### ISSUE TITLE
✨ [Feat] - tester의 directory 구조 및 예외처리

### ISSUE THREAD

**Issue by ohhamma** [web42serv/webserv#20]
## 📝 Description
- 디렉토리인 경우에는 경로 맨 끝에 `/`이 무조건 있어야함
- `/directory/` 아래에 있는 파일을 찾지 못하면 해당 디렉토리 내에서 `youpi.bad_extension`으로 가게끔 설정

## ✅ To-do
- [x] 디렉토리인지 아닌지 확실히 구별하기 (통과한 테케 중 4번 9번 재확인)
- [x] 디렉토리 구조 수정 (`Yeah/`를 `directory/` 밑으로)
- [x] 존재하지 않는 파일일 때, 해당 디렉토리에서 `youpi.bad_extension` 찾을 수 있게 설정
- [x] 그 파일조차도 못 찾으면 `404`으로 가는지 확인

## 📚 Etc
- 자세한 내용은 #14 참고
