### ISSUE TITLE
🎨 [Refactor] - 기능별 함수 재분류

### ISSUE THREAD

**Issue by ohhamma** [web42serv/webserv#35]
## 📝 Description
- 추상적인 기능 기준으로 함수들 재분류 필요

## ✅ To-do
- [ ] `http` 폴더에서 재분류
- [ ] `parser` 폴더에서 재분류
- [ ] `server` 폴더에서 재분류

## 📚 Etc
- 특이사항
